praca/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations",passwords: "passwords"}
  resources :ewidencjas
  root to: 'pages#index'

  get 'hello', to: 'pages#contact'

  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

praca/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

praca/app/models/ewidencja.rb
class Ewidencja < ApplicationRecord
  belongs_to :user
  validates_presence_of  :nr

end

praca/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :ewidencjas
end

praca/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

praca/app/controllers/ewidencjas_controller.rb
class EwidencjasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ewidencja, only: [:show, :edit, :update, :destroy]

  # GET /ewidencjas
  # GET /ewidencjas.json



  def index

@ewidencjas = Ewidencja.where(user_id: current_user.id)

    @lata=Array.new
    @ewidencjas.each do |x|
    @lata<<x.data.year


end








  end

  # GET /ewidencjas/1
  # GET /ewidencjas/1.json
  def show
  end

  # GET /ewidencjas/new
  def new
    @ewidencja = current_user.ewidencjas.build
  end

  # GET /ewidencjas/1/edit
  def edit
  end

  # POST /ewidencjas
  # POST /ewidencjas.json
  def create
    @ewidencja = current_user.ewidencjas.build(ewidencja_params)

    respond_to do |format|
      if @ewidencja.save
        format.html { redirect_to @ewidencja, notice: 'Dodano nowy wpis do Ewidencji.' }
        format.json { render :show, status: :created, location: @ewidencja }
      else
        format.html { render :new }
        format.json { render json: @ewidencja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ewidencjas/1
  # PATCH/PUT /ewidencjas/1.json
  def update
    respond_to do |format|
      if @ewidencja.update(ewidencja_params)
        format.html { redirect_to @ewidencja, notice: 'Ewidencja została zaktualizowana.' }
        format.json { render :show, status: :ok, location: @ewidencja }
      else
        format.html { render :edit }
        format.json { render json: @ewidencja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ewidencjas/1
  # DELETE /ewidencjas/1.json
  def destroy
    @ewidencja.destroy
    respond_to do |format|
      format.html { redirect_to ewidencjas_url, notice: 'Usunięto wpis z Ewidencji.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ewidencja
      @ewidencja = Ewidencja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ewidencja_params
      params.require(:ewidencja).permit(:data, :nr, :przychod, :wydatki, :uwagi)
    end
end

praca/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

praca/app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  prepend_before_action :check_captcha, only: [:create]

  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new
      respond_with_navigational(resource) { render :new }
    end
  end
end

praca/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.

  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        respond_with_navigational(resource) { render :new }
      end
    end
end

praca/app/helpers/application_helper.rb
module ApplicationHelper
end

praca/app/helpers/ewidencjas_helper.rb
module EwidencjasHelper

end

praca/app/helpers/pages_helper.rb
module PagesHelper
end

praca/app/helpers/passwords_helper.rb
module PasswordsHelper
end

praca/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

praca/app/views/ewidencjas/_form.html.erb
<%= form_for(ewidencja) do |f| %>
  <% if ewidencja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ewidencja.errors.count, "error") %> prohibited this ewidencja from being saved:</h2>

      <ul>
      <% ewidencja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %>
    <%= f.date_select :data %>
  </div>

  <div class="field">
    <%= f.label :nr %>
    <%= f.text_field :nr %>
  </div>

  <div class="field">
    <%= f.label :przychod %>
    <%= f.text_field :przychod %>
  </div>

  <div class="field">
    <%= f.label :wydatki %>
    <%= f.text_field :wydatki %>
  </div>

  <div class="field">
    <%= f.label :uwagi %>
    <%= f.text_area :uwagi %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

praca/app/views/ewidencjas/edit.html.erb
<h1>Editing Ewidencja</h1>

<%= render 'form', ewidencja: @ewidencja %>

<%= link_to 'Show', @ewidencja %> |
<%= link_to 'Back', ewidencjas_path %>

praca/app/views/ewidencjas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ewidencja</h1>

<div class="table-responsive">
<table class="table table-bordered">





 <%@lata.uniq.sort.each do |y| %>
<%@nr=1%>
 <% @przychody=0.00 %>
<%@rozchody=0.00%>
<%@styczen=0.00%>
<%@luty=0.00%>
<%@marzec=0.00%>
<%@kwiecien=0.00%>
<%@maj=0.00%>
<%@czerwiec=0.00%>
<%@lipiec=0.00%>
<%@sierpien=0.00%>
<%@wrzesien=0.00%>
<%@pazdziernik=0.00%>
<%@listopad=0.00%>
<%@grudzien=0.00%>

<div class="table-responsive">

<table class="table table-bordered">
  <thead>
    <tr>
      <th>numer</th>
      <th>Data</th>
      <th>Nr dowodu</th>
      <th>Przychod</th>
      <th>Wydatki</th>
      <th>Uwagi</th>
      <th colspan="3"></th>
    </tr>
  </thead>


    <% @ewidencjas.each do |ewidencja| %>
    <% if y==ewidencja.data.year%>

<tbody>
      <tr>
      <td><%=@nr%></td>
        <td><%= ewidencja.data %></td>
        <td><%= ewidencja.nr %></td>
        <td><%= ewidencja.przychod %></td>
        <td><%= ewidencja.wydatki %></td>
        <td><%= ewidencja.uwagi %></td>
        <td><%= link_to 'Show', ewidencja %></td>
        <td><%= link_to 'Edit', edit_ewidencja_path(ewidencja) %></td>
        <td><%= link_to 'Destroy', ewidencja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%@nr=@nr+1%>
     <%@przychody=@przychody+ewidencja.przychod%>
     <%@rozchody=@rozchody+ewidencja.wydatki%>

     <%case ewidencja.data.mon%>
     <%when 1%>
     <%@styczen= @styczen+ewidencja.przychod-ewidencja.wydatki%>
     <%when 2%>
     <%@luty+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 3%>
     <%@marzec+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 4%>
     <%@kwiecien+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 5%>
     <%@maj+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 6%>
     <%@czerwiec+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 7%>
     <%@lipiec+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 8%>
     <%@sierpien+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 9%>
     <%@wrzesien+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 10%>
     <%@pazdziernik+=ewidencja.przychod-ewidencja.wydatki%>
     <%when 11%>
     <%@listopad+=ewidencja.przychod-ewidencja.wydatki%>
      <%when 12%>
     <%@grudzien+=ewidencja.przychod-ewidencja.wydatki%>


<%end%>
      </tr>

<% end %>


    <%end%>

<tr>
        <td></td>
        <td></td>
        <td></td>
        <td>SUMA: <strong><%=@przychody%></strong></td>
        <td>SUMA: <strong><%=@rozchody%></strong></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>

<%=y%>
<p><strong>BILANS ROCZNY: <%=@przychody-@rozchody%></strong></p>
<p>bilans miesieczny</p>
<ul>
<li>Styczeń: <%=@styczen%></li>
<li>Luty: <%=@luty%></li>
<li>Marzec: <%=@marzec%></li>
<li>Kwiecień: <%=@kwiecien%></li>
<li>Maj: <%=@maj%></li>
<li>Czerwiec: <%=@czerwiec%></li>
<li>Lipiec: <%=@lipiec%></li>
<li>Sierpień: <%=@sierpien%></li>
<li>Wrzesień: <%=@wrzesien%></li>
<li>Październik: <%=@pazdziernik%></li>
<li>Listopad: <%=@listopad%></li>
<li>Grudzień: <%=@grudzien%></li>
</ul>
    <%end%>


      </tr>
  </tbody>
</table>

</div>

<br>

<%= link_to 'Dodaj wpis do ewidencji', new_ewidencja_path %>

praca/app/views/ewidencjas/new.html.erb
<h1>New Ewidencja</h1>

<%= render 'form', ewidencja: @ewidencja %>

<%= link_to 'Back', ewidencjas_path %>

praca/app/views/ewidencjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @ewidencja.data %>
</p>

<p>
  <strong>Nr:</strong>
  <%= @ewidencja.nr %>
</p>

<p>
  <strong>Przychod:</strong>
  <%= @ewidencja.przychod %>
</p>

<p>
  <strong>Wydatki:</strong>
  <%= @ewidencja.wydatki %>
</p>

<p>
  <strong>Uwagi:</strong>
  <%= @ewidencja.uwagi %>
</p>

<%= link_to 'Edit', edit_ewidencja_path(@ewidencja) %> |
<%= link_to 'Back', ewidencjas_path %>

praca/app/views/layouts/_foot.html.erb
<%# if current_user %>
<footer class="footer-distributed">
<div class="footer-right">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>
</div>
<div class="footer-left">
<p class="footer-links">
·
<a class="page-scroll" href="#portfolio">Contact Us</a>
·
<a class="page-scroll" href="#services">About Us</a>
·
</p>
<p> </p>
</div>
</footer>

<%# else %>

praca/app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AgroArkusz", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<%if current_user%>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <%end%>
      <ul class="nav navbar-nav navbar-right">

<%if current_user%>
<li><%= link_to "Ewidencja", ewidencjas_path %></li>
<%end%>
      <li><%= link_to "O nas", pages_about_path %></li>
      <li><%= link_to "Kontakt", hello_path %></li>
        <li><%= link_to "Załóż konto", new_user_registration_path if !current_user%></li>
        <li><%= link_to "Zaloguj się", new_user_session_path if !current_user %></li>

       <%if current_user%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%> <span class="caret"></span></a>


          <ul class="dropdown-menu">
            <li><%= link_to "Moje konto", edit_user_registration_path %></li>

            <li role="separator" class="divider"></li>
             <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>
          </ul>
          <%end%>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

praca/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgroArkusz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%=render 'layouts/nav' %>
<%= bootstrap_flash %>
    <div class='container'>
    <%= yield %>
    </div>
   <!-- <%=render 'layouts/foot' %> -->
  </body>
</html>

praca/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

praca/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

praca/app/views/pages/index.html.erb
<div class="container">
<h1>AgroArkusz</h1>
<%if !current_user %>
<p>Witamy na stronie AgroArkusz</p>

<p>Zaloguj się lub załóż konto</p>
<%else%>
<p>Witaj <%= current_user.email%></p>
<p>Jesteś zalogowany</p>
<%end%>
<%if !current_user %>
<%= button_to "Zaloguj się", new_user_session_path,
       :method => :get %>

<%= button_to "Załóż konto", new_user_registration_path,
       :method => :get %>
       <%end%>
</div>